# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: John Walasik
email: jfwalasik3@gmail.com.com
description: >- # this means to ignore newlines until "baseurl:"
  Portfolio and website
baseurl: "/writer" # the subpath of your site, e.g. /blog
url: "https://jfwalasik.github.io" # the base hostname & protocol for your site, e.g. http://example.com
icon: /assets/images/icon-512.png
# twitter_username: 
github_username:  JFWalasik

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


<!-- 
collections:
  AI writing:
    output: true
    permalink: /AI writing/:name/
  writing:
    output: true
    permalink: /writing/:name/
  projects:
    output: true
    permalink: /projects/:name/
  notes:
    output: true
    permalink: /notes/:name/
  recipes:
    output: true
    permalink: /recipes/:name/
  travel:
    output: true
    permalink: /travel/:name/
  music:
    output: true
    permalink: /music/:name/
  books:
    output: true
    permalink: /books/:name/
  art:
    output: true
    permalink: /art/:name/
  code:
    output: true
    permalink: /code/:name/

defaults:
  - scope:
      type: "AI writing"
    values:
      layout: "post"
  - scope:
      type: "writing"
    values:
      layout: "post" 
  --> 
  # ... repeat for other collections


plugins:
  - jekyll-paginate

paginate: 3
paginate_path: "/page/:num/"
