# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: John Walasik
email: jfwalasik3@gmail.com.com
description: >- # this means to ignore newlines until "baseurl:"
  Portfolio and website
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "https://jfwalasik.github.io" # the base hostname & protocol for your site, e.g. http://example.com
icon: /assets/images/icon-512.png
# twitter_username: 
github_username:  JFWalasik

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-paginate

collections:
  ai_writing:
    output: true
    title: "AI Writing"
    permalink: /ai-writing/:name/
  citation_maps:
    output: true
    title: "Citation Maps for O-1, EB-1 Petitions"
    permalink: /citation-maps/:name/
  short_writing_samples:
    output: true
    title: "Short Writing Samples"
    permalink: /short-writing-samples/:name/
  immigration_writing:
    output: true
    title: "Immigration Writing"
    permalink: /immigration-writing/:name/
  code:
    output: true
    title: "Code (Citation Map Generator, Simple Blockchain)"
    permalink: /code/:name/
  security_training:
    output: true
    title: "Security Training"
    permalink: /security-training/:name/
  walkthroughs_sops:
    output: true
    title: "Walkthroughs, SOPs, Work Instructions"
    permalink: /walkthroughs-sops/:name/
  other_legal_writing:
    output: true
    title: "Other Legal Writing (SOW, CLRA)"
    permalink: /other-legal-writing/:name/
  authentication_flows:
    output: true
    title: "Authentication Flows"
    permalink: /authentication-flows/:name/
  infrastructure:
    output: true
    title: "Infrastructure - Kickstarting Bare Metal Servers with Verdad"
    permalink: /infrastructure/:name/
  powerdms:
    output: true
    title: "PowerDMS - Gdocs vs MSWord"
    permalink: /powerdms/:name/
  i_believe:
    output: true
    title: "I Believe"
    permalink: /i-believe/:name/
  weather_modification:
    output: true
    title: "Weather Modification"
    permalink: /weather-modification/:name/

defaults:
  - scope:
      type: "ai_writing"
    values:
      layout: "post"
  - scope:
      type: "citation_maps"
    values:
      layout: "post"
  - scope:
      type: "short_writing_samples"
    values:
      layout: "post"
  - scope:
      type: "immigration_writing"
    values:
      layout: "post"
  - scope:
      type: "code"
    values:
      layout: "post"
  - scope:
      type: "security_training"
    values:
      layout: "post"
  - scope:
      type: "walkthroughs_sops"
    values:
      layout: "post"
  - scope:
      type: "other_legal_writing"
    values:
      layout: "post"
  - scope:
      type: "authentication_flows"
    values:
      layout: "post"
  - scope:
      type: "infrastructure"
    values:
      layout: "post"
  - scope:
      type: "powerdms"
    values:
      layout: "post"
  - scope:
      type: "i_believe"
    values:
      layout: "post"
  - scope:
      type: "weather_modification"
    values:
      layout: "post"
      
google_analytics: G-5V25JC8DHG

paginate: 3
paginate_path: "/page/:num/"
